[pytest]
minversion = 8.0

testpaths = api/tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    -ra
    -v
    --strict-markers

markers =
    ithaka: tests relacionados a Ithaka API
    nettra: tests relacionados a Nettra API
    smoke: pruebas críticas de alto impacto
    regression: suite completa de regresión
    contract: validaciones de contrato (Schemathesis)
    integration: pruebas de integración contra entorno real