[pytest]
minversion = 8.0
pythonpath = .

testpaths = api/tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    -ra
    -v
    --strict-markers

markers =
    ithaka: tests relacionados a Ithaka API
    nettra: tests relacionados a Nettra API
    functional: Tests funcionales
    contract: Tests de contrato OpenAPI - validaciones de contrato (Schemathesis)
    smoke: pruebas críticas de alto impacto
    security: Tests relacionados con autenticación/autorización
    regression: suite completa de regresión
    integration: pruebas de integración contra entorno real
    slow: Tests que pueden demorar